### ISSUE TITLE
cmake Fails on Linux Mint

### ISSUE THREAD

**Issue by Bug725** [mborgerson/fatx#12]
Unable to generate make file.
was error:
 cmake
Usage
  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>...
...
Run 'cmake --help' for more information.

**** I had to specify :

cmake Unix Makefiles /home/bug725/fatx/src
cd ~/fatx/src
make

That took care of it for me. Please add a notation.

I do need to do a distro update system. My cat /etc/*release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
cat: /etc/upstream-release: Is a directory

**Comment by mborgerson** [comment]
This is a couple years old by now, but I don't expect this is an issue any more. Please let me know if it's still causing you problems
