### ISSUE TITLE
Feature request: F and G partitions support.

### ISSUE THREAD

**Issue by rizaumami** [mborgerson/fatx#30]
The write capability is amazing, but the lack of F and G partitions support make `fatxfs` somewhat limited as these partitions are where we store our games.

**Comment by GXTX** [comment]
Support is already there, you just need to specify offset and size.

**Comment by rizaumami** [comment]
The problem is, I don't know what offset or size of my disk's partitions are.
`fdisk -l` didn't work as it doesn't know what FATX is.
The only thing I cant think of is using XBPartitioner on ogxbox to see disk partitions size.

**Comment by mborgerson** [comment]
Partitions are hardcoded now, but we can take a look at automatically discovering partition sizes based on how other tools do so

**Comment by mborgerson** [comment]
Here's xbpartitioner source for reference: https://github.com/opcow/XBpartitioner/blob/main/PartInfo.cpp

**Comment by rizaumami** [comment]
`testdisk` can list the ogxbox disk partition.
Here is a 1 TB disk with F partition take all the space:

```bash
TestDisk 7.1, Data Recovery Utility, July 2019
Christophe GRENIER <grenier@cgsecurity.org>
https://www.cgsecurity.org
Please wait...
Disk /dev/sdc - 1000 GB / 931 GiB - CHS 121601 255 63
Sector size:512
Model: TOSHIBA MQ01ABD100

Disk /dev/sdc - 1000 GB / 931 GiB - CHS 121601 255 63
     Partition			Start        End    Size in sectors
 1 P FATX                     0  16 17    95 172 13    1536000
     FATX
 2 P FATX                    95 172 14   191  73 10    1536000
     FATX
 3 P FATX                   191  73 11   286 229  7    1536000
     FATX
 4 P FATX                   286 229  8   350 163  5    1024000
     FATX
 5 P FATX                   350 163  6 121601  80 63 1947892144
     FATX

```

Can I use that info to manually mount the partition?

**Comment by GXTX** [comment]
That almost looks broken to me. You have 5 partitions by default, what's odd is the size of your last one which should be `Z:\` which is a cache partition.

**Comment by rizaumami** [comment]
All the partition is there except E.
But if I mount (using `--drive` or `offset/size`) it's successfully mounted.

**Comment by rizaumami** [comment]
CMIIW, the offset for F would be `0x1ddd80000`?

```bash
$ sudo fatxfs -o allow_other /dev/sdc ogxhdd --offset=0xddd80000 --size=0xe834f36000
failed to initialize the filesystem
```

Still no dice. But if the offset is correct, all I need to do is to calculate the of F?

**Comment by GXTX** [comment]
Not all kernels use the "partition table", it's a scene made up thing, some kernels will have hard set offsets for F/G.

**Comment by rizaumami** [comment]
Ah, yes.  
As I've read, the original HDD not using partition table. But stored the hard coded partition offset and size in its BIOS.  
The "partition table" rising after `XBPartitioner` use.
