### ISSUE TITLE
fatxfs is a directory

### ISSUE THREAD

**Issue by joneldiablo** [mborgerson/fatx#53]
I'm trying to build the fatxfs binary, but after `make`

(image from readme)
=====
![image](https://user-images.githubusercontent.com/13206502/175429418-c3abb8cc-3f52-4ec4-b25d-48581e2dcc47.png)
=====

 trying to use the command:
 ```
./fatxfs /dev/nbd0 c_drive
```
I get this error: `fatxfs is a directory`

I check it with `ls ./fatxfs`

and its right, that is a directory....
sooooo
where is the binary o.O

**Comment by mborgerson** [comment]
Check inside the fatxfs directory
