### ISSUE TITLE
failed to initialize the filesystem

### ISSUE THREAD

**Issue by patatetom** [mborgerson/fatx#6]
hello,

with fatxfs now compiled, I'm trying to access a 250GB hard disk of Xbox 360 Slim, but every time I try, I come across "failed to initialize the filesystem": can you help me, put me on the right track ?

```
# fatxfs --help
FATXFS - Userspace FATX Filesystem Driver

Usage: fatxfs <device> <mountpoint> [<options>]
   or: fatxfs <device> <mountpoint> --drive=c|e|x|y|z [<options>]
   or: fatxfs <device> <mountpoint> --offset=<offset> --size=<size> [<options>]

General Options:
    -o opt, [opt...]       mount options
    -h --help              print help
    -V --version           print version

FATXFS options:
    --drive=<letter>       mount a partition by its drive letter
    --offset=<offset>      specify the offset (in bytes) of a partition manually
    --size=<size>          specify the size (in bytes) of a partition manually
    --log=<log path>       enable fatxfs logging
    --loglevel=<level>     control the log output level (a higher value yields more output)
...
```

the hard disk is accessible through `/dev/loop1` :
```
# fatxfs /dev/loop1 /mountpoint/
failed to initialize the filesystem
```
with drive letter as in your example :
```
# fatxfs /dev/loop1 /mountpoint/ --drive=e
failed to initialize the filesystem
```

with offset and size of data partition :
```
# dd if=/dev/loop1 bs=1 count=4 skip=$((0x130eb0000)) status=none
XTAF

# fdisk -l /dev/loop1
Disque /dev/loop1 : 232,9 GiB, 250059350016 octets, 488397168 secteurs
Unités : secteur de 1 × 512 = 512 octets
Taille de secteur (logique / physique) : 512 octets / 512 octets
taille d'E/S (minimale / optimale) : 512 octets / 512 octets

# fatxfs /dev/loop1 /mountpoint/ --log=/tmp/log --loglevel=20 --offset=$((0x130eb0000)) --size=$((250059350016-0x130eb0000))
failed to initialize the filesystem

# cat /tmp/log 
fatx_dev_read(buf=0x0x7ffeed71cf2c, size=0x4, items=0x1)
invalid signature
```
the value `0x130eb0000` is comming from http://www.free60.org/wiki/FATX.

regards, lacsaP.

**Comment by mborgerson** [comment]
I'm not sure about the Xbox 360 filesystem, and if it is the same as the original Xbox FATX filesystem. From a brief glance at the link you sent, they seem to be different. If they are similar enough, I encourage you to add the necessary changes and file a pull request. Otherwise, there seem to be a number of 360 FS reading tools on GitHub you might be able to use.

**Comment by patatetom** [comment]
hello Matt,

I'm sorry to come back in this closed issue, but I need your lights.

I followed your advice : I duplicated your repository and started looking at how your code works and the problem seems to be endianness... it starts as soon as the signature check : `0x46415458` is read while `0x58544146` is expected.

I know very little about the C language : how can I force reading some numbers in big endian or little endian ?

regards, lacsaP.

**Comment by patatetom** [comment]
I've added this :

```diff
diff --git a/src/fatx_partition.c b/src/fatx_partition.c
index 23482c2..627637b 100644
--- a/src/fatx_partition.c
+++ b/src/fatx_partition.c
@@ -18,6 +18,7 @@
  */
 
 #include "fatx_internal.h"
+#include <arpa/inet.h>
 
 /*
  * Check partition signature.
@@ -41,7 +42,7 @@ int fatx_check_partition_signature(struct fatx_fs *fs)
         return -1;
     }
 
-    if (signature != FATX_SIGNATURE)
+    if (htonl(signature) != FATX_SIGNATURE)
     {
         fatx_error(fs, "invalid signature\n");
         return -1;
```

do you know a simpler and/or more elegant way ?

regards, lacsaP.
